DROP SCHEMA IF EXISTS sec;
CREATE SCHEMA sec;

use sec;

CREATE TABLE box
(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  label text NOT NULL,
  deleted TINYINT UNSIGNED DEFAULT 0,
  CONSTRAINT box_pkey PRIMARY KEY (id)
);